<?php
/**
 * Plugin Name: OpenCampaigns for WooCommerce
 * Description: Publish your products as OpenCampaigns using the Nostr network.
 * Version: 1.0.0
 * Author: OpenCampaigns
 */

if (!defined('ABSPATH')) {
    exit;
}

class OpenCampaignsWooPlugin {

    public function __construct() {
        // Admin menus & settings
        add_action('admin_menu', [$this, 'add_admin_menu']);
        add_action('admin_init', [$this, 'register_settings']);
        
        // Meta Boxes on Products
        add_action('add_meta_boxes', [$this, 'add_product_meta_box']);
        add_action('save_post_product', [$this, 'save_product_meta']);
        
        // Rewrite rules for .well-known
        add_action('init', [$this, 'add_rewrite_rules']);
        add_filter('query_vars', [$this, 'add_query_vars']);
        add_action('template_redirect', [$this, 'handle_endpoint']);
        
        // Admin JS for crypto signing
        add_action('admin_enqueue_scripts', [$this, 'enqueue_admin_scripts']);
        
        // AJAX endpoint for saving signatures generated by the browser SDK
        add_action('wp_ajax_opencampaigns_save_payload', [$this, 'ajax_save_payload']);
    }

    public function add_admin_menu() {
        add_options_page(
            'OpenCampaigns',
            'OpenCampaigns',
            'manage_options',
            'opencampaigns',
            [$this, 'settings_page_html']
        );
    }

    public function register_settings() {
        register_setting('opencampaigns_group', 'opencampaigns_pubkey');
        register_setting('opencampaigns_group', 'opencampaigns_privkey');
        register_setting('opencampaigns_group', 'opencampaigns_brand_name');
        register_setting('opencampaigns_group', 'opencampaigns_tracking_engine');
    }

    public function settings_page_html() {
        if (!current_user_can('manage_options')) {
            return;
        }
        ?>
        <div class="wrap" id="opencampaigns-admin-wrap">
            <h1>OpenCampaigns Settings</h1>
            <form action="options.php" method="post">
                <?php
                settings_fields('opencampaigns_group');
                do_settings_sections('opencampaigns_group');
                ?>
                <table class="form-table">
                    <tr>
                        <th scope="row">Brand Name</th>
                        <td><input type="text" name="opencampaigns_brand_name" value="<?php echo esc_attr(get_option('opencampaigns_brand_name')); ?>" /></td>
                    </tr>
                    <tr>
                        <th scope="row">Nostr Public Key (Hex)</th>
                        <td><input type="text" id="oc_pubkey" name="opencampaigns_pubkey" value="<?php echo esc_attr(get_option('opencampaigns_pubkey')); ?>" style="width: 400px;" readonly /></td>
                    </tr>
                    <tr>
                        <th scope="row">Nostr Private Key (Hex)</th>
                        <td>
                            <input type="password" id="oc_privkey" name="opencampaigns_privkey" value="<?php echo esc_attr(get_option('opencampaigns_privkey')); ?>" style="width: 400px;" />
                            <br/><button type="button" id="oc_generate_keys" class="button">Generate New Keys</button>
                            <p class="description">Your private key stays in your local database to sign campaigns.</p>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Tracking Engine Config (JSON)</th>
                        <td>
                            <textarea name="opencampaigns_tracking_engine" rows="5" style="width: 400px;"><?php echo esc_attr(get_option('opencampaigns_tracking_engine', '{"engine":"custom", "parameters":[{"key":"utm_source","value":"opencampaigns"}]}')); ?></textarea>
                        </td>
                    </tr>
                </table>
                <?php submit_button(); ?>
            </form>
            <hr/>
            <h2>Sync & Sign Campaigns</h2>
            <p>Because OpenCampaigns require cryptographic Schnorr signatures, we build and sign the campaign manifest securely here in your browser.</p>
            <button type="button" id="oc_sync_campaigns" class="button button-primary">Generate & Sign Campaigns</button>
            <div id="oc_sync_result" style="margin-top: 10px;"></div>
        </div>
        <?php
    }

    public function add_product_meta_box() {
        add_meta_box(
            'opencampaigns_meta_box',
            'OpenCampaigns Promotion',
            [$this, 'render_product_meta_box'],
            'product',
            'side',
            'high'
        );
    }

    public function render_product_meta_box($post) {
        $publish = get_post_meta($post->ID, '_opencampaigns_publish', true);
        $tags = get_post_meta($post->ID, '_opencampaigns_tags', true);
        wp_nonce_field('opencampaigns_meta_box_nonce', 'opencampaigns_nonce');
        ?>
        <p>
            <label>
                <input type="checkbox" name="opencampaigns_publish" value="yes" <?php checked($publish, 'yes'); ?> />
                Publish to OpenCampaigns
            </label>
        </p>
        <p>
            <label for="opencampaigns_tags">Tags (comma separated):</label>
            <input type="text" id="opencampaigns_tags" name="opencampaigns_tags" value="<?php echo esc_attr($tags); ?>" style="width: 100%;" />
        </p>
        <?php
    }

    public function save_product_meta($post_id) {
        if (!isset($_POST['opencampaigns_nonce']) || !wp_verify_nonce($_POST['opencampaigns_nonce'], 'opencampaigns_meta_box_nonce')) return;
        if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) return;
        
        if (isset($_POST['opencampaigns_publish'])) {
            update_post_meta($post_id, '_opencampaigns_publish', 'yes');
        } else {
            update_post_meta($post_id, '_opencampaigns_publish', 'no');
        }
        
        if (isset($_POST['opencampaigns_tags'])) {
            update_post_meta($post_id, '_opencampaigns_tags', sanitize_text_field($_POST['opencampaigns_tags']));
        }
    }

    public function add_rewrite_rules() {
        add_rewrite_rule('^\.well-known/opencampaigns\.json$', 'index.php?opencampaigns_api=1', 'top');
    }

    public function add_query_vars($vars) {
        $vars[] = 'opencampaigns_api';
        return $vars;
    }

    public function handle_endpoint() {
        if (get_query_var('opencampaigns_api') == '1') {
            $payload = get_option('opencampaigns_signed_payload', '{}');
            header('Content-Type: application/json');
            header('Access-Control-Allow-Origin: *');
            echo $payload;
            exit;
        }
    }

    public function enqueue_admin_scripts($hook) {
        if ($hook !== 'settings_page_opencampaigns') return;
        
        // We will build a small JS bundle that uses the @opencampaigns/sdk
        wp_enqueue_script('opencampaigns-admin-js', plugin_dir_url(__FILE__) . 'assets/admin.js', [], '1.0.0', true);
        
        // Pass data to JS
        wp_localize_script('opencampaigns-admin-js', 'ocData', [
            'ajax_url' => admin_url('admin-ajax.php'),
            'nonce'    => wp_create_nonce('oc_sync_nonce'),
            'pubkey'   => get_option('opencampaigns_pubkey'),
            'privkey'  => get_option('opencampaigns_privkey'),
            'brand'    => get_option('opencampaigns_brand_name'),
            'website'  => site_url(),
            'tracking' => json_decode(get_option('opencampaigns_tracking_engine', '{}'), true)
        ]);
    }

    public function ajax_save_payload() {
        check_ajax_referer('oc_sync_nonce', 'nonce');
        
        if (!current_user_can('manage_options')) {
            wp_send_json_error('Unauthorized');
        }

        $payload = isset($_POST['payload']) ? stripslashes($_POST['payload']) : '';
        if (empty($payload)) {
            wp_send_json_error('Empty payload');
        }

        update_option('opencampaigns_signed_payload', $payload);
        
        // Bonus: Actually push the Nostr Event using server side logic, 
        // OR the JS can do it before hitting this endpoint.
        // It's better for the JS SDK to handle Nostr event publishing!
        
        wp_send_json_success('Successfully updated JSON.');
    }
}

new OpenCampaignsWooPlugin();
